### ISSUE TITLE
Possible issues in Optax

### ISSUE THREAD

**Issue by TomLiZh** [NicolasZucchet/minimal-LRU#2]
Hello,

I am implementing the following code:
`python run_train.py --dataset cifar-classification --epochs 180`

However, I'm encountering an issue and the error message I'm receiving is as follows:
```
File "/minimal-LRU/lru/train_helpers.py", line 87, in create_train_state
    params = variables["params"].unfreeze()
AttributeError: 'dict' object has no attribute 'unfreeze'
```
I search Optax documentation, but no clues for the function "unfreeze".  Could you kindly guide me on any necessary modifications? Thank you in advance for your time and support.

Here is some information about my environment:
```
optax==0.1.7
jax==0.4.14
```

**Comment by NicolasZucchet** [comment]
Hello,

This comes from the new version of Flax (0.7.1). Downgrading to flax==0.6.10 should solve the issue.
I'm updating the requirements of the repo accordingly.

**Comment by JuanFMontesinos** [comment]
Adding some extra info, for that given version of flax jax needs to be <0.4.23 
In 0.4.24 there are some dependencies that flax import from jax already deprecated.

**Comment by NicolasZucchet** [comment]
I've migrated the repo to work with Jax 0.4.24 and Flax 0.8.1.

**Comment by JuanFMontesinos** [comment]
Amazing, thanks!
